// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuv2I6wTSTaVqyKi5vGRdqmlNKBf_cVNg',
    appId: '1:374105398036:web:bef688d1b7d89d4a900001',
    messagingSenderId: '374105398036',
    projectId: 'analytica-4932f',
    authDomain: 'analytica-4932f.firebaseapp.com',
    storageBucket: 'analytica-4932f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4OlYkR2Ynx5RfeUirC9BcyqXnjb_e2D8',
    appId: '1:374105398036:android:1afe383482e388c1900001',
    messagingSenderId: '374105398036',
    projectId: 'analytica-4932f',
    storageBucket: 'analytica-4932f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUkjA1n76BZ978TXIVT2dKfaSeD_Uw_AU',
    appId: '1:374105398036:ios:bd5fc92410d3bbe1900001',
    messagingSenderId: '374105398036',
    projectId: 'analytica-4932f',
    storageBucket: 'analytica-4932f.firebasestorage.app',
    androidClientId: '374105398036-0o7cn3m57va5jt4qkuavi710l7tklhi5.apps.googleusercontent.com',
    iosClientId: '374105398036-ohnhadn6lbdmvbll1foun407s9ost7sq.apps.googleusercontent.com',
    iosBundleId: 'com.analytica.analytica',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUkjA1n76BZ978TXIVT2dKfaSeD_Uw_AU',
    appId: '1:374105398036:ios:bd5fc92410d3bbe1900001',
    messagingSenderId: '374105398036',
    projectId: 'analytica-4932f',
    storageBucket: 'analytica-4932f.firebasestorage.app',
    androidClientId: '374105398036-0o7cn3m57va5jt4qkuavi710l7tklhi5.apps.googleusercontent.com',
    iosClientId: '374105398036-ohnhadn6lbdmvbll1foun407s9ost7sq.apps.googleusercontent.com',
    iosBundleId: 'com.analytica.analytica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuv2I6wTSTaVqyKi5vGRdqmlNKBf_cVNg',
    appId: '1:374105398036:web:d9efacbfd06457ef900001',
    messagingSenderId: '374105398036',
    projectId: 'analytica-4932f',
    authDomain: 'analytica-4932f.firebaseapp.com',
    storageBucket: 'analytica-4932f.firebasestorage.app',
  );

}